package app

import (
	"io"
	"log/slog"
	"testing"
	"time"
)

func TestBackgroundJobSchedulerProcessesDueJobsOnStartupTick(t *testing.T) {
	store := NewStore()

	product, err := store.CreateProduct(Product{
		Name:  "Scheduler Product",
		SKU:   "SCHED-1",
		Stock: 2,
	})
	if err != nil {
		t.Fatalf("expected product create: %v", err)
	}

	due := time.Now().UTC().Add(-2 * time.Hour)
	_, err = store.CreateOrder(
		"Scheduler Client",
		[]SaleItem{{ProductID: product.ID, Quantity: 1, Price: 100}},
		false,
		nil,
		"UAH",
		&due,
	)
	if err != nil {
		t.Fatalf("expected order create: %v", err)
	}

	job, err := store.EnqueueOverdueReminderJob(time.Now().UTC().Add(-time.Minute))
	if err != nil {
		t.Fatalf("expected enqueue job: %v", err)
	}

	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	scheduler := NewBackgroundJobScheduler(store, logger, 25*time.Millisecond)
	scheduler.Start()
	defer scheduler.Stop()

	deadline := time.Now().Add(2 * time.Second)
	for time.Now().Before(deadline) {
		jobs, err := store.ListBackgroundJobs(10)
		if err != nil {
			t.Fatalf("expected list jobs: %v", err)
		}
		for _, item := range jobs {
			if item.ID == job.ID && item.Status == BackgroundJobStatusCompleted {
				notifications, err := store.ListNotifications(10)
				if err != nil {
					t.Fatalf("expected list notifications: %v", err)
				}
				if len(notifications) == 0 {
					t.Fatalf("expected notifications generated by scheduled job")
				}
				return
			}
		}
		time.Sleep(20 * time.Millisecond)
	}

	jobs, err := store.ListBackgroundJobs(10)
	if err != nil {
		t.Fatalf("expected list jobs after waiting: %v", err)
	}
	t.Fatalf("expected scheduler to process job %d, jobs=%+v", job.ID, jobs)
}
